version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
     - '27017:27017'
    volumes:
     - 'mongo_data:/data/db'
    networks:
     - app
    
  redis:
    image: 'redis:alpine'
    command: redis-server
    environment: 
      - REDIS_REPLICATION_MODE=master
    ports:
      - '6379:6379'
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - 'redis_data:/bitnami/redis/data'
    networks:
      - app
 
  code-paste:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - mongo
      - redis
    ports:
      - '3000:3000'
    links:
      - mongo
      - redis
    networks:
      - app
volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local

networks:
  app:
    driver: bridge     
